name: Build Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Convert coverage to lcov (para usar em relatórios de cobertura)
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura;lcov'

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: coveragereport
