name: Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Front-end
        run: cd View

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: cd View && npm install

      - name: Build
        run: cd View && npm run build

      - name: Run tests with coverage
        run: |
          cd View
          npm run test -- --coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: View/coverage
